# Generated by Django 5.2.5 on 2025-10-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default_pic.png", null=True, upload_to="profiles/"
            ),
        ),
    ]
