# Generated by Django 5.2.5 on 2025-10-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_profile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
