# Generated by Django 5.2.5 on 2025-10-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_category_tag_blog_comment_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
    ]
