# Generated by Django 5.2.5 on 2025-11-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("followers", "Followers Only"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
