# Generated by Django 5.2.5 on 2025-11-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_follow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="follow",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
